<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Users.aspx.cs" Inherits="TodoList.User.Users" %>

<asp:Content ID="Content1" ContentPlaceHolderID="cphTitle" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphHead" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="cplMenu" runat="server">
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="cphBody" runat="server">
    <asp:GridView ID="gvUser" runat="server"
        DataSourceID="odsUser"
        AutoGenerateColumns="false"
        CssClass="table table-striped"
        AllowPaging="true"
        AllowSorting="true"
        DataKeyNames="Id"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true">

        <Columns>
            <asp:BoundField HeaderText="Login" DataField="Login" />
            <asp:BoundField HeaderText="Email" DataField="Email" />
            <asp:BoundField HeaderText="FirstName" DataField="FirstName" />
            <asp:BoundField HeaderText="SurName" DataField="SurName" />
            <asp:BoundField HeaderText="Password" DataField="Pass" />
        </Columns>
    </asp:GridView>
</asp:Content>
<asp:Content ID="Content5" ContentPlaceHolderID="cphFooter" runat="server">
</asp:Content>
