<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Tasks.aspx.cs" Inherits="TodoList.Tasks" %>

<asp:Content ID="cMenu" ContentPlaceHolderID="cplMenu" runat="server">
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="cphHead" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="cphBody" runat="server">

    <asp:GridView ID="gvTask" runat="server"
        DataSourceID="odsTask"
        AutoGenerateColumns="false"
        CssClass="table table-striped"
        AllowPaging="true"
        AllowSorting="true"
        OnSorting="gvTask_Sorting"
        DataKeyNames="Id"
        AutoGenerateDeleteButton="true"
        AutoGenerateEditButton="true"
        AutoGenerateSelectButton="true">
        <%-- <Columns>
            <asp:TemplateField HeaderText="Tasks">
                <ItemTemplate>
                   <%# Eval("title") %>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Created">
                <ItemTemplate>
                   <%# Eval("Created") %>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Deadline">
                <ItemTemplate>
                   <%# Eval("Deadline") %>
                </ItemTemplate>
            </asp:TemplateField>

            <asp:TemplateField HeaderText="Done">
                <ItemTemplate>
                   <%# Eval("IsDone") %>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>--%>
        <Columns>
            <asp:TemplateField HeaderText="Title">
                <ItemTemplate>
                    <a href="ShowTask.aspx?taskId=<%# Eval("Id") %>" data-id="<%# Eval("Id") %>" data-entity="Task">
                        <%# Eval("Title") %> 
                    </a>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField HeaderText="Text" DataField="Text" />
            <asp:BoundField HeaderText="Created" DataField="Created" />
            <asp:BoundField HeaderText="Done?" DataField="IsDone" />
        </Columns>
    </asp:GridView>
    <asp:ScriptManager ID="smAjax" runat="server" EnablePageMethods="true"></asp:ScriptManager>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="cphFooter" runat="server">
</asp:Content>
